name: barbu_score
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.32.8"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1
  equatable: ^2.0.7
  firebase_analytics: ^11.4.6
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  flutter_circular_text: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  intl: any
  json_annotation: ^4.9.0
  non_uniform_border: ^1.0.0
  reorderable_grid_view: ^2.2.8
  rive: 0.13.1
  shared_preferences: ^2.5.3
  timelines_plus: ^1.0.7
  two_dimensional_scrollables: ^0.3.5
  wakelock_plus: ^1.3.2
  turn_page_transition:
    git:
      url: https://github.com/Zigotote/turn_page_transition

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  mockito: ^5.4.5
  patrol_finders: ^2.8.2
  json_serializable: ^6.9.0
  meta: any

# Run with dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  ios: false
  image_path: "assets/logo.png"

# Run with dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/flags/
    - assets/icons/dark/
    - assets/icons/light/
    - assets/players/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-SemiBold.ttf
